# Generated by Django 2.2 on 2019-11-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
