# Generated by Django 2.2.4 on 2019-12-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
