# Generated by Django 2.2 on 2019-04-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
