# Generated by Django 2.2 on 2019-04-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20190414_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='name',
            new_name='title',
        ),
    ]
