# Generated by Django 2.2 on 2019-04-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20190414_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='title',
            new_name='name',
        ),
    ]
