# Generated by Django 2.2 on 2019-04-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_auto_20190414_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='wyl',
            field=models.TextField(blank=True),
        ),
    ]
