# Generated by Django 2.2 on 2019-04-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0013_glossary'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='../static/default.jpg', upload_to='images/'),
        ),
    ]
