# Generated by Django 2.2 on 2019-04-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0017_auto_20190421_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.FileField(blank=True, upload_to='sources/'),
        ),
    ]
