# Generated by Django 2.2 on 2019-04-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0018_auto_20190421_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
