# Generated by Django 2.2 on 2019-04-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0019_resource_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
