# Generated by Django 2.2 on 2019-04-29 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0020_section_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={},
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
    ]
