# Generated by Django 2.2 on 2019-04-29 17:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0021_auto_20190429_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sectionorder',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=None),
        ),
    ]
