# Generated by Django 2.2 on 2019-05-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0026_auto_20190503_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
