# Generated by Django 2.2 on 2019-05-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0027_auto_20190503_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='successrate',
            field=models.IntegerField(default=0),
        ),
    ]
