# Generated by Django 2.2 on 2019-05-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0028_quiz_successrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='isTrue',
            field=models.BooleanField(default=False),
        ),
    ]
