# Generated by Django 2.2 on 2019-05-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0029_choice_istrue'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
