# Generated by Django 2.2 on 2019-05-11 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0032_auto_20190511_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glossary',
            old_name='name',
            new_name='label',
        ),
    ]
