# Generated by Django 2.2 on 2019-05-13 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('topics', '0034_auto_20190511_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner_Course_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinished', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Learner')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_learner',
            field=models.ManyToManyField(blank=True, through='topics.Learner_Course_Record', to='accounts.Learner'),
        ),
    ]
