# Generated by Django 2.2 on 2019-05-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('topics', '0035_auto_20190513_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner_Section_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinished', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Learner')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='course_learner',
            field=models.ManyToManyField(blank=True, through='topics.Learner_Section_Record', to='accounts.Learner'),
        ),
    ]
