# Generated by Django 2.2 on 2019-05-14 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('topics', '0036_auto_20190513_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='course_learner',
            new_name='section_learner',
        ),
        migrations.CreateModel(
            name='Learner_Quiz_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinished', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Learner')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Learner_Lecture_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinished', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Learner')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Lecture')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_learner',
            field=models.ManyToManyField(blank=True, through='topics.Learner_Lecture_Record', to='accounts.Learner'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_learner',
            field=models.ManyToManyField(blank=True, through='topics.Learner_Quiz_Record', to='accounts.Learner'),
        ),
    ]
