# Generated by Django 2.2 on 2019-05-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0037_auto_20190514_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='isLinked',
            field=models.BooleanField(default=False),
        ),
    ]
