# Generated by Django 2.2 on 2019-05-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0038_section_islinked'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner_course_record',
            name='completeRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learner_section_record',
            name='completeRate',
            field=models.IntegerField(default=0),
        ),
    ]
