# Generated by Django 2.2 on 2019-05-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0046_auto_20190521_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner_course_record',
            name='completeRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='learner_section_record',
            name='completeRate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
