# Generated by Django 2.2 on 2019-05-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0047_auto_20190521_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='completeRate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='learner_course_record',
            name='completeRate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='learner_section_record',
            name='completeRate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='section',
            name='completeRate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
