# Generated by Django 2.2 on 2019-12-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0049_auto_20190521_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityStream_JSON',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=200)),
                ('summary', models.CharField(blank=True, max_length=200)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('actor', models.CharField(blank=True, max_length=200)),
                ('object', models.CharField(blank=True, max_length=200)),
                ('published', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
