# Generated by Django 2.2 on 2019-12-07 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0050_activitystream_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='label',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
