# Generated by Django 2.2.4 on 2019-12-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0051_auto_20191207_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='glossary',
            name='identifier',
            field=models.CharField(default='', max_length=32),
        ),
    ]
