# Generated by Django 2.2.4 on 2019-12-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0052_glossary_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetActivityStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
