# Generated by Django 2.2.4 on 2019-12-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0053_getactivitystream'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystream_json',
            name='imgUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
